eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 35
    status-page-url: https://localhost/8080/info
    health-check-url: https://localhost/8080/health
    home-page-url: https://localhost/8080/
server:
  port: 0
spring:
  application:
    name: client